<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>annotations</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <Version>2.1.0</Version>
    <Authors>FN</Authors>
    <Description>Fastest PNG decoder for .NET and C#</Description>
    <Copyright>Copyright (c) FN 2026</Copyright>
    <PackageProjectUrl>https://github.com/FireNameFN/GreenPng.Workspace</PackageProjectUrl>
    <PackageReadmeFile Condition="$(IncludeReadme) == true">README.md</PackageReadmeFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageTags>png image decode decoder load loader deserialize deserializer</PackageTags>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="" Condition="$(IncludeReadme) == true" />
    <None Include="LICENSE.txt" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GreenBuf\GreenBuf.csproj" />
  </ItemGroup>

</Project>
